# Generated by Django 5.2.6 on 2025-10-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_exam_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set(),
        ),
    ]
